version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file:
      - .env

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - uploaded_files:/data

    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env

  celery:
    build: .
    command: celery -A report_generator worker -l info
    volumes:
      - .:/code
      - uploaded_files:/data

    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env

  celerybeat:
    build: .
    command: celery -A report_generator beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env

volumes:
  postgres_data:
  uploaded_files:
