# Generated by Django 4.2.11 on 2024-05-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotstatus',
            name='chassis_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
